apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: shopmicro
data:
  mimir.yaml: |
    target: all
    server:
      http_listen_port: 9009
    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /data
    blocks_storage:
      filesystem:
        dir: /data/blocks
    compactor:
      data_dir: /data/compactor
    distributor:
      ring:
        kvstore:
          store: memberlist
    ingester:
      ring:
        kvstore:
          store: memberlist
    ruler_storage:
      filesystem:
        dir: /data/ruler
    store_gateway:
      sharding_ring:
        kvstore:
          store: memberlist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir:latest
        args:
        - -config.file=/etc/mimir/mimir.yaml
        - -target=all
        ports:
        - containerPort: 9009
        volumeMounts:
        - name: config
          mountPath: /etc/mimir
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: mimir-config
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: shopmicro
spec:
  selector:
    app: mimir
  ports:
  - port: 9009
    targetPort: 9009