apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: shopmicro
  labels:
    app: ml-service
    tier: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
        tier: ml
    spec:
      containers:
      - name: ml-service
        image: shopmicro-ml-service:v2
        imagePullPolicy: Never
        env:
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: REDIS_URL
          value: "redis://redis:6379"
        ports:
        - containerPort: 5000
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: shopmicro
  labels:
    app: ml-service
    tier: ml
spec:
  selector:
    app: ml-service
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  type: ClusterIP